### ISSUE TITLE
Removing Default Padding in IOS

### ISSUE THREAD

**Issue by HasnainAD** [jacklam718/react-native-modals#159]
How to remove the default padding in IOS, I want to have two buttons on top and each will take 50% of the screen, but there is padding on both sides of buttons, I also made the rounded to false but to have no impact at all. Other things I have done is give style to dialogStyle, which has both padding and margin set to 0, again to have no impact at all.

**Comment by fpena** [comment]
You can get around this by doing:
```
<DialogContent
    style={{ 
        paddingLeft: 0,
        paddingRight: 0,
        paddingBottom: 0,
    }}
>
```

**Comment by pixelize** [comment]
or just don't use `DialogContent` and replace with a `<View />` and style it in your own way ;)
