### ISSUE TITLE
yellowbox !! AppRegistry.setWrapperComponentProvider

### ISSUE THREAD

**Issue by kalmndo** [jacklam718/react-native-modals#207]
AppRegistry.setWrapperComponentProvider has no effect in managed Expo apps. You can instead wrap your app root component to achieve an identical result.

i dont exactly know about it, but i think this is a bug?

**Comment by afshawnlotfi** [comment]
Same thing happening to me

**Comment by DavidBHanby** [comment]
> 
> 
> Same thing happening to me, and nothing is showing up

Exactly the same here since Expo SDK 36 upgrade. I'm using his 'React Native Popup Dialog', yet the github link directs to here. 

Are you using 'React Native Popup Dialog' or JackLam718's newer lib > react-native-modals ? Wondering if I need to switch over to fix... ?

**Comment by afshawnlotfi** [comment]
> > Same thing happening to me, and nothing is showing up
> 
> Exactly the same here since Expo SDK 36 upgrade. I'm using his 'React Native Popup Dialog', yet the github link directs to here.
> 
> Are you using 'React Native Popup Dialog' or JackLam718's newer lib > react-native-modals ? Wondering if I need to switch over to fix... ?

I am not using the newer lib so I assume the former. I also have this problem after Expo 36 though. It works in my other projects with previous versions of Expo.

**Comment by serhiipalash** [comment]
I've submitted a pr in Expo to fix it https://github.com/expo/expo/pull/6530

**Comment by DavidBHanby** [comment]
> 
> 
> I've submitted a pr in Expo to fix it [expo/expo#6530](https://github.com/expo/expo/pull/6530)

@serhiipalash  Thank you. Excellent. Your pr fixes the issue. I copied in your changes directly as running the expo upgrade didn't yet add the changes

**Comment by serhiipalash** [comment]
@DavidBHanby np. Also FYI modals (popups) don't work only in development. The fix is not needed for your production bundle, but of course it's hard to develop something without seeing that it actually works.

**Comment by DavidBHanby** [comment]
@serhiipalash That's good to know. I'd suspected that may be so from the <DevAppContainer>. Thanks for clarifying.

**Comment by brentvatne** [comment]
this is resolved in the latest patch version of the `expo` package. you can set it 36.0.1 in package.json and install to get it.

sorry for the hassle, i thought this was an unused private api, i wasn't aware that any libraries actually hooked into it

**Comment by jacklam718** [comment]
@serhiipalash @brentvatne Awesome!
Thank you very much.
