### ISSUE TITLE
Problem with using modal with redux

### ISSUE THREAD

**Issue by MasoudShah** [jacklam718/react-native-modals#212]
I want to show and hide modal using redux, and as a result, modal visibility depends on component props. It has a very common use case. For example I want to show modal by clicking on a flatlist Item and that modal exists in the containing list component. When I call redux function, the props get updated but the modal doesn't show up. After clicking somewhere it shows up for some milliseconds and get dismissed immediately (because of clicking outside functionality). How can I overcome this problem.

**Comment by onelittlebird** [comment]
You need to make the redux store available for the views rendered in the modal (as it's not rendered in the same heirarchy).
`<Modal>
  <ModalContent>
    <Provider store={store}>
      {children}
    </Provider>
  </ModalContent>
</Modal>`

**Comment by jacklam718** [comment]
This problem has been resolved in version `v0.20.1`
