### ISSUE TITLE
package doesn't work with latest expo 36.0.2

### ISSUE THREAD

**Issue by abdougenesis** [jacklam718/react-native-modals#219]
**environment**
expo CLI 3.11.7
system:
OS : linux 18
binaries:
Yarn: 1.21.1
npm: 6.12.0

target for IOS & Android

Steps to Reproduce

1. create a new expo project with expo init command ( or any current project with expo 36.0.2)
2. install react-native-modals library `yarn add react-native-modals`
3. use the library example in the app.js file
4. type any button to open the example

**expected behavior**
modal window should appear when any button is pressed

**actual behavior**

modal not showing

change expo to 35.0.0 and test again and it will work

**Comment by charanjit-singh** [comment]
why?

**Comment by jacklam718** [comment]
Upgraded to expo sdk 40
