### ISSUE TITLE
Animated.event now requires a second argument for options , which leads to the second error `useNativeDriver` was not specified.

### ISSUE THREAD

**Issue by Abhishek12345679** [jacklam718/react-native-modals#234]

**Comment by Kasun-thilina** [comment]
Any solutions? The modal view seems to be getting duplicated on visible event. and the useNativeDriver error comes from the duplicated modal. ( I figured this out because I use a video player inside the modal and the video is getting played twice. The sounds are overlapping )

**Comment by Abhishek12345679** [comment]
@Kasun-thilina  i suggest using react-native-modal that is much more easier to setup
