### ISSUE TITLE
Modal: `key` is not a prop. 

### ISSUE THREAD

**Issue by YonAnnKv** [jacklam718/react-native-modals#246]
Warning: Modal: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)

**Comment by YonAnnKv** [comment]
{
    .
     "react": "16.13.1",
     "react-native": "0.63.3",
    .
    .
    "react-native-modals": "^0.20.1",
    .
    .
}

**Comment by xkungfu** [comment]
same issue!
"react-native-modals": "^0.22.1",

**Comment by jacklam718** [comment]
@xkungfu @YonAnnKv Should be fixed in `v0.22.3`
