### ISSUE TITLE
[example demo] Uncaught Error: Can not use Modal component until ModalPortal is mounted

### ISSUE THREAD

**Issue by xkungfu** [jacklam718/react-native-modals#252]
example with react-native-modals V0.22.2 :
example from:
https://github.com/jacklam718/react-native-modals/tree/master/example

build by expo: expo start web

**Comment by AKclown** [comment]
How to solve this, I also face this problem？

**Comment by Naowak** [comment]
I faced this issue too, the solution is in the docs : you have to import ModalPortal in your root app component like this.

```
import { ModalPortal } from 'react-native-modals';
import { Provider } from 'react-redux';

const Root = () => {
  return (
    <Provider store={store}>
      <App />
      <ModalPortal />
    </Provider>
  );
}
```
