### ISSUE TITLE
[version:0.22.2]Warning: BottomModal: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop

### ISSUE THREAD

**Issue by xkungfu** [jacklam718/react-native-modals#253]
warning after clicked button, and the dilog opened:

`Warning: BottomModal: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop
`

**Comment by jacklam718** [comment]
duplicated #246
