### ISSUE TITLE
ScrollView dialog position.

### ISSUE THREAD

**Issue by Vitaly-V** [jacklam718/react-native-modals#47]
Hello! First of all - thanks for this library.

I have an difficulty with dialog position on the ScrollView. My ScrollView has a few forms with close button and I want to show "Are you sure?  YES/NO" dialog when user clicks on close button. 
But I don't know how I can center dialog window at the middle of a device screen. Does someone have some experience with it?

**Comment by mishrabhinav** [comment]
@Vitaly-V can you please post a snippet of your code?

**Comment by egemon** [comment]
@Vitaly-V @mishrabhinav https://github.com/jacklam718/react-native-popup-dialog/issues/93
