### ISSUE TITLE
PopupDialog is cut off inside DrawerNavigator

### ISSUE THREAD

**Issue by Dror-Bar** [jacklam718/react-native-modals#97]
Hey,
I'm using the popular navigation library [react-navigation](https://github.com/react-navigation/react-navigation).
When trying to show the popupDialog inside of the DrawerNavigator, the popup is cut off by the side menu. Example:

![screen shot 2018-02-07 at 10 03 34](https://user-images.githubusercontent.com/34343333/35905199-e26d4ff4-0bee-11e8-9a25-e3c4f469ee22.png)

I assume this happens because it counts as a child of the side menu. The problem is, I have no idea how to put the popupMenu in the same layer, and then calling it from the menu (I'm using a custom component too). Is there any solution to this?

**Comment by jacklam718** [comment]
@Dror-Bar I think you could put the dialog on outside of the or out side the MenuDrawer or of outside of DrawerNavigator.

**Comment by Dror-Bar** [comment]
@jacklam718 yeah I think so too, but how would I call it? Right now I'm importing it and using it like this:
```
class DrawerMenu extends Component  {

...

    render() {
        return (
            <View>
                <PopupMenu />
            </View>
        );
    }
}
```
How can I use the PopupMenu without using it inside render function? I think you have an example for react-native-router-flux, but I'm not sure how to accomplish this with react-navigation.
If relevant, here is some sample code of my architecture:
```
export const RootNavigator = StackNavigator({

    Login: { screen: Login },
    Main: { screen: Drawer }, // Drawer is actually my DrawerNavigator
});
```
And my App.js:
```
import React, { Component } from 'react';
import { RootNavigator } from './components/Router';

export default class MainApp extends Component {

  render() {
    return <RootNavigator />;
  }
}
```

**Comment by jacklam718** [comment]
@Dror-Bar Are you using redux?

**Comment by Dror-Bar** [comment]
Nope unfortunately  =)

**Comment by syntaxiom** [comment]
I would like to know how to do this, too. I can't find anything on the internet that'll help with this.

**Comment by jacklam718** [comment]
@syntaxiom This may useful for you https://github.com/jacklam718/react-native-popup-dialog/issues/42#issuecomment-310028245

**Comment by mzhr** [comment]
@Dror-Bar @syntaxiom I got passed trying to render a full screen popup by putting the popup inside a Modal component from the react-native package. Though I'm not sure if this works inside DrawerNavigation.

**Comment by jacklam718** [comment]
Can use imperative api instead
